{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubecron.fullname" . }}
  labels:
    {{- include "kubecron.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubecron.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubecron.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
