{{- if and (eq (include "kubecron.mode" .) "server") .Values.api.token (not .Values.api.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubecron.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubecron.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-token: {{ .Values.api.token | quote }}
{{- end }}
