{{- if and (not .Values.kubeconfigs.existingSecret) (.Values.kubeconfigs.data) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubecron.fullname" . }}-kubeconfigs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubecron.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $k, $v := .Values.kubeconfigs.data }}
  {{ $k }}: {{ $v }}
  {{- end }}
{{- end }}
