root = "."
tmp_dir = "/tmp/air"

[build]
  cmd = "templ generate && go build -o /tmp/air/kubecron ./cmd/kubecron"
  bin = "/tmp/air/kubecron"
  include_ext = ["go", "templ", "css", "sql"]
  exclude_dir  = ["dev", "charts", ".git", "tmp"]
  exclude_regex = ["_templ\\.go$"]
  delay = 500
  kill_delay = "0s"
  rerun = false
  poll = true
  poll_interval = 500

[log]
  time = false
  main_only = false

[color]
  main    = "magenta"
  watcher = "cyan"
  build   = "yellow"
  runner  = "green"

[misc]
  clean_on_exit = true
